---
title: "ABM Individual Data Processing and Statistics"
author: "@MinaAlmasi & @drasbaek"
date: "6/2/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse)
```

## Loading the data 
```{r}
#ind_data <- read_csv("/Users/minaalmasi/Desktop/ABM-study-group/data_1000_sim/1000sim_ind_data.csv")

ind_data <- read_csv("/Users/minaalmasi/Desktop/ABM-study-group/data_100_sim/15ticks_100sim_ind_data.csv")
```
```{r}
group_data <- read_csv("/Users/minaalmasi/Desktop/ABM-study-group/data_100_sim/15ticks_100sim_group_data.csv")
```


```{r}
colnames(ind_data)
```

### Diversity Level 
```{r}
repeated_data <- group_data[rep(seq_len(nrow(group_data)), each = 4), ] 

ind_data$diversity_score <- repeated_data$diversity_score
```

```{r}
ind_data$diversity <- cut(ind_data$diversity_score, 
                      breaks = c(-Inf, 2, 5, Inf),
                      labels = c("low", "middle", "high"))
```

```{r}
ind_data$diversity <- as.factor(ind_data$diversity)
ind_data$type <- as.factor(ind_data$type)
```

```{r}
mean_values <- ind_data %>%
  group_by(type) %>% 
  summarise("mean_avg_adaptation" = mean(avg_adaptation), 
            "sd_mean_avg_adaptation" = sd(avg_adaptation))

mean_values

mean_values %>%
  mutate(type = fct_reorder(type, mean_avg_adaptation)) %>%
  ggplot(aes(x=type, y=mean_avg_adaptation, color = type)) +
    geom_point(stat="identity") +
    labs(x = "Adaptation", y = "Personality Type (PT)", title = "Personality Type and Adaptation")+
    theme_bw() + 
    guides(color=FALSE)
```

### Accuracy 
```{r}
ggplot(data = ind_data, aes(x = type, y = avg_accuracy, fill = type)) + 
  labs(title = "Accuracy")+
  geom_violin()
```

```{r}
ggplot(data = ind_data, aes(x = avg_accuracy, y = avg_adaptation)) + 
  labs(title = "Accuracy and Adaptation")+
  geom_point(aes(color = type)) + 
  theme_bw()
```

```{r}
adaptation_fig <- ind_data %>%
  mutate(type = fct_reorder(type, avg_adaptation, .desc = TRUE)) %>%
  ggplot(aes(x=type, y=avg_adaptation, fill = type)) +
    geom_violin() +
    geom_boxplot(width = 0.4, outlier.size=-1) + 
    scale_y_continuous(labels = scales::percent_format(accuracy=1))+
    labs(y = "Adaptation", x = "Personality Type (PT)", title = "(A) Personality Type and Adaptation")+
    stat_summary(fun = mean, geom = "point", shape = 18, size=2, colour="white", alpha = 0.8)+ 
    theme_bw() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.title = element_text(hjust = 0.5, size = 16), text=element_text(family = "Times New Roman"))+
    guides(fill=FALSE)


#ggsave(adaptation_fig, filename = "adaptation_ind_data.jpeg", dpi = 300, type = "cairo", width = 7, height = 3.5, units = "in")

adaptation_fig
```

## STATS 
```{r}
## accuracy model ## 
accuracy_model <- lm(avg_accuracy ~ type, data = ind_data)
summary(accuracy_model)
```

```{r}
## adaptation model ## 
adaptation_model <- lm(avg_adaptation ~ type, data = ind_data)
summary(adaptation_model)
```

